name: proyect_polaris
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: ^2.3.3

  flutter_lints: ^2.0.0
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/rounded_logo.png"
  adaptive_icon_background: "assets/images/rounded_logo.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Image Assets
    - assets/images/
    - assets/images/planets/mars/
    - assets/images/planets/earth/
    - assets/images/planets/jupiter/
    - assets/images/planets/mercury/
    - assets/images/planets/neptune/
    - assets/images/planets/saturn/
    - assets/images/planets/uranus/
    - assets/images/planets/venus/
    - assets/images/planets/
    - assets/images/onlyplanets/

    # Docs Assets
    - assets/docs/
  
#Splash Native
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/rounded_logo.png"

  android_12:
    image: "assets/images/rounded_logo.png"
    color: "#ffffff"

